name: bytes
description: A library for working with bytes.
version: 0.3.0
author: Steven Roose <stevenroose@gmail.com>
homepage: https://github.com/stevenroose/dart-bytes

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
